[application]

# App name
name = "Taigla"

default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "Taigla"
base_path = "."

[web.watcher]
reload_html = true
index_on_404 = true
watch_path = ["src", "public"]

[web.resource]
style = ["tailwind.css"]
script = []

[web.resource.dev]
style = []
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"
